# Generated by Django 3.2.2 on 2021-05-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('price', models.IntegerField(verbose_name='')),
                ('discount', models.FloatField(verbose_name='')),
                ('special_discount', models.FloatField(verbose_name='')),
                ('special_discount_time', models.DateTimeField(verbose_name='')),
                ('number', models.IntegerField(verbose_name='')),
                ('description', models.TextField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='')),
            ],
        ),
    ]
