# Generated by Django 3.2.2 on 2021-06-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210613_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidbar',
            name='header',
            field=models.CharField(blank=True, max_length=300, verbose_name='header'),
        ),
        migrations.AddField(
            model_name='slidbar',
            name='product_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='slidbar',
            name='title',
            field=models.CharField(max_length=300, verbose_name='title'),
        ),
    ]
